"""Embedded NPPS4 master DB CREATE TABLE SQL for Android/Chaquopy.

Chaquopy may package Python modules as bytecode-only assets, so reading
npps4/db/*.py at runtime is unreliable.  This module is generated from the
NPPS4 db modules at source-package time and used by cn_honoka_master.py.
"""

SCHEMAS = {'achievement': {'achievement_category_m': 'CREATE TABLE `achievement_category_m` (\n'
                                           '        `achievement_category_id` INTEGER NOT NULL,\n'
                                           '        `start_date` TEXT,\n'
                                           '        `end_date` TEXT,\n'
                                           '        `display_flag` INTEGER NOT NULL,\n'
                                           '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                           '        PRIMARY KEY (`achievement_category_id`)\n'
                                           '    )',
                 'achievement_filter_category_m': 'CREATE TABLE `achievement_filter_category_m` (\n'
                                                  '        `achievement_filter_category_id` INTEGER NOT NULL,\n'
                                                  '        `name` TEXT,\n'
                                                  '        `name_en` TEXT,\n'
                                                  '        `icon_asset` TEXT,\n'
                                                  '        `icon_asset_en` TEXT,\n'
                                                  '        `default_select_flag` INTEGER,\n'
                                                  '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                                  '        PRIMARY KEY (`achievement_filter_category_id`)\n'
                                                  '    )',
                 'achievement_m': 'CREATE TABLE `achievement_m` (\n'
                                  '        `achievement_id` INTEGER NOT NULL,\n'
                                  '        `title` TEXT,\n'
                                  '        `title_en` TEXT,\n'
                                  '        `description` TEXT,\n'
                                  '        `description_en` TEXT,\n'
                                  '        `achievement_type` INTEGER NOT NULL,\n'
                                  '        `reset_type` INTEGER NOT NULL,\n'
                                  '        `reset_param` INTEGER,\n'
                                  '        `params1` INTEGER,\n'
                                  '        `params2` INTEGER,\n'
                                  '        `params3` INTEGER,\n'
                                  '        `params4` INTEGER,\n'
                                  '        `params5` INTEGER,\n'
                                  '        `params6` INTEGER,\n'
                                  '        `params7` INTEGER,\n'
                                  '        `params8` INTEGER,\n'
                                  '        `params9` INTEGER,\n'
                                  '        `params10` INTEGER,\n'
                                  '        `params11` INTEGER,\n'
                                  '        `start_date` TEXT NOT NULL,\n'
                                  '        `end_date` TEXT,\n'
                                  '        `default_open_flag` INTEGER NOT NULL,\n'
                                  '        `display_flag` INTEGER NOT NULL,\n'
                                  '        `achievement_filter_category_id` INTEGER NOT NULL,\n'
                                  '        `achievement_filter_type_id` INTEGER NOT NULL,\n'
                                  '        `auto_reward_flag` INTEGER NOT NULL,\n'
                                  '        `display_start_date` TEXT,\n'
                                  '        `open_condition_string` TEXT,\n'
                                  '        `open_condition_string_en` TEXT,\n'
                                  '        `term_invisible_flag` INTEGER,\n'
                                  '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                  '        PRIMARY KEY (`achievement_id`)\n'
                                  '    )',
                 'achievement_story_m': 'CREATE TABLE `achievement_story_m` (\n'
                                        '        `achievement_id` INTEGER NOT NULL,\n'
                                        '        `next_achievement_id` INTEGER NOT NULL,\n'
                                        '        PRIMARY KEY (`achievement_id`,`next_achievement_id`)\n'
                                        '    )',
                 'achievement_tag_m': 'CREATE TABLE `achievement_tag_m` (\n'
                                      '        `achievement_id` INTEGER NOT NULL,\n'
                                      '        `achievement_category_id` INTEGER NOT NULL,\n'
                                      '        PRIMARY KEY (`achievement_id`,`achievement_category_id`)\n'
                                      '    )',
                 'achievement_unit_type_group_m': 'CREATE TABLE `achievement_unit_type_group_m` (\n'
                                                  '        `achievement_unit_type_group_id` INTEGER NOT NULL,\n'
                                                  '        `unit_type_id` INTEGER NOT NULL,\n'
                                                  '        `rank` INTEGER NOT NULL,\n'
                                                  '        PRIMARY KEY '
                                                  '(`achievement_unit_type_group_id`,`unit_type_id`)\n'
                                                  '    )'},
 'effort': {'live_effort_point_box_spec_m': 'CREATE TABLE `live_effort_point_box_spec_m` (\n'
                                            '        `live_effort_point_box_spec_id` INTEGER NOT NULL,\n'
                                            '        `capacity` INTEGER NOT NULL,\n'
                                            '        `limited_capacity` INTEGER NOT NULL,\n'
                                            '        `num_rewards` INTEGER NOT NULL,\n'
                                            '        `closed_asset` TEXT NOT NULL,\n'
                                            '        `closed_asset_en` TEXT,\n'
                                            '        `opened_asset` TEXT NOT NULL,\n'
                                            '        `opened_asset_en` TEXT,\n'
                                            '        `box_asset` TEXT NOT NULL,\n'
                                            '        `box_asset_en` TEXT,\n'
                                            '        `login_box_asset` TEXT NOT NULL,\n'
                                            '        `login_box_asset_en` TEXT,\n'
                                            '        `movie_name` TEXT NOT NULL,\n'
                                            '        `movie_name_en` TEXT,\n'
                                            '        `asset_se_id` INTEGER NOT NULL,\n'
                                            '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                            '        PRIMARY KEY (`live_effort_point_box_spec_id`)\n'
                                            '    )'},
 'exchange': {'exchange_festival_point_unit_m': 'CREATE TABLE `exchange_festival_point_unit_m` (\n'
                                                '        `unit_id` INTEGER NOT NULL,\n'
                                                '        PRIMARY KEY (`unit_id`)\n'
                                                '    )',
              'exchange_nopoint_unit_m': 'CREATE TABLE `exchange_nopoint_unit_m` (\n'
                                         '        `unit_id` INTEGER NOT NULL,\n'
                                         '        PRIMARY KEY (`unit_id`)\n'
                                         '    )',
              'exchange_point_m': 'CREATE TABLE `exchange_point_m` (\n'
                                  '        `exchange_point_id` INTEGER NOT NULL,\n'
                                  '        `name` TEXT NOT NULL,\n'
                                  '        `name_en` TEXT,\n'
                                  '        `small_asset` TEXT NOT NULL,\n'
                                  '        `small_asset_en` TEXT,\n'
                                  '        `icon_asset` TEXT NOT NULL,\n'
                                  '        `icon_asset_en` TEXT,\n'
                                  '        `middle_asset` TEXT,\n'
                                  '        `middle_asset_en` TEXT,\n'
                                  '        `r_rank_up_point` INTEGER,\n'
                                  '        `sr_rank_up_point` INTEGER,\n'
                                  '        `ssr_rank_up_point` INTEGER,\n'
                                  '        `ur_rank_up_point` INTEGER,\n'
                                  '        `sort` INTEGER NOT NULL,\n'
                                  '        `start_date` TEXT,\n'
                                  '        `end_date` TEXT,\n'
                                  '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                  '        PRIMARY KEY (`exchange_point_id`)\n'
                                  '    )'},
 'game_mater': {'add_type_m': 'CREATE TABLE `add_type_m` (\n'
                              '        `add_type` INTEGER NOT NULL,\n'
                              '        `name` TEXT NOT NULL,\n'
                              '        `name_en` TEXT,\n'
                              '        `small_asset` TEXT,\n'
                              '        `small_asset_en` TEXT,\n'
                              '        `middle_asset` TEXT,\n'
                              '        `middle_asset_en` TEXT,\n'
                              '        `large_asset` TEXT,\n'
                              '        `large_asset_en` TEXT,\n'
                              '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                              '        PRIMARY KEY (`add_type`)\n'
                              '    )',
                'game_setting_m': 'CREATE TABLE `game_setting_m` (\n'
                                  '        `game_setting_id` INTEGER NOT NULL,\n'
                                  '        `live_loveca_for_energy` INTEGER NOT NULL,\n'
                                  '        `live_energy_recoverly_time` INTEGER NOT NULL,\n'
                                  '        `live_social_point_for_others` INTEGER NOT NULL,\n'
                                  '        `live_social_point_for_friend` INTEGER NOT NULL,\n'
                                  '        `live_social_point_for_alliance` INTEGER NOT NULL,\n'
                                  '        `live_loveca_for_continue` INTEGER NOT NULL,\n'
                                  '        `live_attribute_bonus_rate` REAL NOT NULL,\n'
                                  '        `live_notes_touch_voice_rate` REAL NOT NULL,\n'
                                  '        `live_gameover_card_cnt` INTEGER NOT NULL,\n'
                                  '        `live_skill_gauge_cnt` INTEGER NOT NULL,\n'
                                  '        `live_skill_need_score` INTEGER NOT NULL,\n'
                                  '        `live_other_count` INTEGER NOT NULL,\n'
                                  '        `live_other_level_range` INTEGER NOT NULL,\n'
                                  '        `live_unclear_love_minus` INTEGER NOT NULL,\n'
                                  '        `reward_available_term` INTEGER NOT NULL,\n'
                                  '        `navigation_replacement_rate` INTEGER NOT NULL,\n'
                                  '        `navigation_speak_time` INTEGER NOT NULL,\n'
                                  '        `friend_invite_message` TEXT NOT NULL,\n'
                                  '        `friend_invite_message_en` TEXT,\n'
                                  '        `scenario_ending_message` TEXT NOT NULL,\n'
                                  '        `scenario_ending_message_en` TEXT,\n'
                                  '        `alliance_level_for_making` INTEGER NOT NULL,\n'
                                  '        `alliance_game_coin_for_making` INTEGER NOT NULL,\n'
                                  '        `deck_max` INTEGER NOT NULL,\n'
                                  '        `nextday_time` TEXT NOT NULL,\n'
                                  '        `card_ranking_cnt` INTEGER NOT NULL,\n'
                                  '        `coin_alert_min_value` INTEGER NOT NULL,\n'
                                  '        `evolution_attribute_bonus` REAL NOT NULL,\n'
                                  '        `evolution_rankup_coin_rate` REAL NOT NULL,\n'
                                  '        `deck_unit_max` INTEGER NOT NULL,\n'
                                  '        `social_point_max` INTEGER NOT NULL,\n'
                                  '        `sns_coin_max` INTEGER NOT NULL,\n'
                                  '        `game_coin_max` INTEGER NOT NULL,\n'
                                  '        `item_max` INTEGER NOT NULL,\n'
                                  '        `initial_game_coin` INTEGER NOT NULL,\n'
                                  '        `shop_loveca_for_unit_max` INTEGER NOT NULL,\n'
                                  '        `shop_unit_max_gain` INTEGER NOT NULL,\n'
                                  '        `unit_max` INTEGER NOT NULL,\n'
                                  '        `waiting_unit_max` INTEGER NOT NULL,\n'
                                  '        `shop_loveca_for_friend_max` INTEGER NOT NULL,\n'
                                  '        `shop_friend_max_gain` INTEGER NOT NULL,\n'
                                  '        `friend_max` INTEGER NOT NULL,\n'
                                  '        `shop_unit_max_limit_cnt` INTEGER NOT NULL,\n'
                                  '        `shop_friend_max_limit_cnt` INTEGER NOT NULL,\n'
                                  '        `festival_material_max` INTEGER NOT NULL,\n'
                                  '        `klab_id_task_start_date` TEXT NOT NULL,\n'
                                  '        `exchange_flag` INTEGER NOT NULL,\n'
                                  '        PRIMARY KEY (`game_setting_id`)\n'
                                  '    )',
                'sort_condition_m': 'CREATE TABLE `sort_condition_m` (\n'
                                    '        `sort_condition_id` INTEGER NOT NULL,\n'
                                    '        `screen_id` INTEGER NOT NULL,\n'
                                    '        `sort_condition_type` INTEGER NOT NULL,\n'
                                    '        `sort_condition_sub_type` INTEGER,\n'
                                    '        `sort_label` TEXT NOT NULL,\n'
                                    '        `sort_label_en` TEXT,\n'
                                    '        PRIMARY KEY (`sort_condition_id`)\n'
                                    '    )',
                'strings_m': 'CREATE TABLE `strings_m` (\n'
                             '        `string_key` TEXT NOT NULL,\n'
                             '        `string_value` TEXT NOT NULL,\n'
                             '        `string_label` TEXT NOT NULL,\n'
                             '        `string_label_en` TEXT,\n'
                             '        PRIMARY KEY (`string_key`,`string_value`)\n'
                             '    )'},
 'item': {'award_m': 'CREATE TABLE `award_m` (\n'
                     '        `award_id` INTEGER NOT NULL,\n'
                     '        `name` TEXT NOT NULL,\n'
                     '        `name_en` TEXT,\n'
                     '        `description` TEXT NOT NULL,\n'
                     '        `description_en` TEXT,\n'
                     '        `img_asset` TEXT NOT NULL,\n'
                     '        `img_asset_en` TEXT,\n'
                     '        `sort` INTEGER NOT NULL,\n'
                     '        `di_asset_display_flag` INTEGER NOT NULL,\n'
                     '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                     '        PRIMARY KEY (`award_id`)\n'
                     '    )',
          'background_m': 'CREATE TABLE `background_m` (\n'
                          '        `background_id` INTEGER NOT NULL,\n'
                          '        `name` TEXT NOT NULL,\n'
                          '        `name_en` TEXT,\n'
                          '        `description` TEXT NOT NULL,\n'
                          '        `description_en` TEXT,\n'
                          '        `img_asset` TEXT NOT NULL,\n'
                          '        `thumbnail_asset` TEXT NOT NULL,\n'
                          '        `sort` INTEGER NOT NULL,\n'
                          '        `background_shader_param_id` INTEGER,\n'
                          '        `background_flash_param_id` INTEGER,\n'
                          '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                          '        PRIMARY KEY (`background_id`)\n'
                          '    )',
          'buff_item_m': 'CREATE TABLE `buff_item_m` (\n'
                         '        `item_id` INTEGER NOT NULL,\n'
                         '        `buff_type` INTEGER NOT NULL,\n'
                         '        `buff_logic` INTEGER NOT NULL,\n'
                         '        `buff_amount` INTEGER NOT NULL,\n'
                         '        `limit_logic` INTEGER NOT NULL,\n'
                         '        `limit_amount` INTEGER NOT NULL,\n'
                         '        `event_id` INTEGER,\n'
                         '        PRIMARY KEY (`item_id`)\n'
                         '    )',
          'buff_item_use_limit_time_m': 'CREATE TABLE `buff_item_use_limit_time_m` (\n'
                                        '        `buff_item_use_limit_time_id` INTEGER NOT NULL,\n'
                                        '        `start_time` TEXT NOT NULL,\n'
                                        '        `end_time` TEXT NOT NULL,\n'
                                        '        PRIMARY KEY (`buff_item_use_limit_time_id`)\n'
                                        '    )',
          'change_delegate_item_amount_m': 'CREATE TABLE `change_delegate_item_amount_m` (\n'
                                           '        `unit_rarity` INTEGER NOT NULL,\n'
                                           '        `item_rarity` INTEGER NOT NULL,\n'
                                           '        `amount` INTEGER NOT NULL,\n'
                                           '        `cost_game_coin_amount` INTEGER NOT NULL,\n'
                                           '        PRIMARY KEY (`unit_rarity`,`item_rarity`)\n'
                                           '    )',
          'change_delegate_item_m': 'CREATE TABLE `change_delegate_item_m` (\n'
                                    '        `item_id` INTEGER NOT NULL,\n'
                                    '        `unit_type_id` INTEGER NOT NULL,\n'
                                    '        `rarity` INTEGER NOT NULL,\n'
                                    '        PRIMARY KEY (`item_id`)\n'
                                    '    )',
          'item_exchange_m': 'CREATE TABLE `item_exchange_m` (\n'
                             '        `item_id` INTEGER NOT NULL,\n'
                             '        `next_item_id` INTEGER NOT NULL,\n'
                             '        `amount` INTEGER NOT NULL,\n'
                             '        `game_coin_amount` INTEGER NOT NULL,\n'
                             '        PRIMARY KEY (`item_id`)\n'
                             '    )',
          'item_expire_m': 'CREATE TABLE `item_expire_m` (\n'
                           '        `add_type` INTEGER NOT NULL,\n'
                           '        `item_id` INTEGER NOT NULL,\n'
                           '        `expire_date` TEXT NOT NULL,\n'
                           '        PRIMARY KEY (`add_type`,`item_id`)\n'
                           '    )',
          'kg_item_m': 'CREATE TABLE `kg_item_m` (\n'
                       '        `item_id` INTEGER NOT NULL,\n'
                       '        `item_tab_id` INTEGER NOT NULL,\n'
                       '        `name` TEXT,\n'
                       '        `name_en` TEXT,\n'
                       '        `item_category_id` INTEGER,\n'
                       '        `item_sub_category_id` INTEGER,\n'
                       '        `effect_value` INTEGER,\n'
                       '        `image_asset` TEXT,\n'
                       '        `image_asset_en` TEXT,\n'
                       '        `icon_image_asset` TEXT,\n'
                       '        `icon_image_asset_en` TEXT,\n'
                       '        `description` TEXT,\n'
                       '        `description_en` TEXT,\n'
                       '        `rank` INTEGER,\n'
                       '        `enhancement_exp_id` INTEGER,\n'
                       '        `enhancement_pattern_id` INTEGER,\n'
                       '        `merchandise_group_id` INTEGER,\n'
                       '        `merchandise_flag` INTEGER NOT NULL,\n'
                       '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                       '        PRIMARY KEY (`item_id`)\n'
                       '    )',
          'live_notes_icon_m': 'CREATE TABLE `live_notes_icon_m` (\n'
                               '        `live_notes_icon_id` INTEGER NOT NULL,\n'
                               '        `name` TEXT NOT NULL,\n'
                               '        `name_en` TEXT,\n'
                               '        `sort` INTEGER NOT NULL,\n'
                               '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                               '        PRIMARY KEY (`live_notes_icon_id`)\n'
                               '    )',
          'live_se_m': 'CREATE TABLE `live_se_m` (\n'
                       '        `live_se_id` INTEGER NOT NULL,\n'
                       '        `name` TEXT NOT NULL,\n'
                       '        `name_en` TEXT,\n'
                       '        `description` TEXT NOT NULL,\n'
                       '        `description_en` TEXT,\n'
                       '        `sort` INTEGER NOT NULL,\n'
                       '        PRIMARY KEY (`live_se_id`)\n'
                       '    )',
          'lottery_ticket_item_m': 'CREATE TABLE `lottery_ticket_item_m` (\n'
                                   '        `item_id` INTEGER NOT NULL,\n'
                                   '        `lottery_ticket_id` INTEGER NOT NULL,\n'
                                   '        PRIMARY KEY (`item_id`)\n'
                                   '    )',
          'memories_m': 'CREATE TABLE `memories_m` (\n'
                        '        `memories_id` INTEGER NOT NULL,\n'
                        '        `img_asset` TEXT NOT NULL,\n'
                        '        `background_shader_param_id` INTEGER,\n'
                        '        `background_flash_param_id` INTEGER,\n'
                        '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                        '        PRIMARY KEY (`memories_id`)\n'
                        '    )',
          'recovery_item_m': 'CREATE TABLE `recovery_item_m` (\n'
                             '        `recovery_item_id` INTEGER NOT NULL,\n'
                             '        `name` TEXT NOT NULL,\n'
                             '        `name_en` TEXT,\n'
                             '        `recovery_type` INTEGER NOT NULL,\n'
                             '        `recovery_value` INTEGER NOT NULL,\n'
                             '        `small_asset` TEXT,\n'
                             '        `small_asset_en` TEXT,\n'
                             '        `middle_asset` TEXT,\n'
                             '        `middle_asset_en` TEXT,\n'
                             '        `large_asset` TEXT,\n'
                             '        `large_asset_en` TEXT,\n'
                             '        `description` TEXT NOT NULL,\n'
                             '        `description_en` TEXT,\n'
                             '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                             '        PRIMARY KEY (`recovery_item_id`)\n'
                             '    )',
          'unit_enhance_item_m': 'CREATE TABLE `unit_enhance_item_m` (\n'
                                 '        `item_id` INTEGER NOT NULL,\n'
                                 '        `unit_id` INTEGER,\n'
                                 '        `rarity` INTEGER,\n'
                                 '        `enhance_type` INTEGER NOT NULL,\n'
                                 '        `enhance_amount` INTEGER NOT NULL,\n'
                                 '        PRIMARY KEY (`item_id`)\n'
                                 '    )',
          'unit_reinforce_item_m': 'CREATE TABLE `unit_reinforce_item_m` (\n'
                                   '        `item_id` INTEGER NOT NULL,\n'
                                   '        `reinforce_type` INTEGER NOT NULL,\n'
                                   '        `addition_value` INTEGER NOT NULL,\n'
                                   '        `event_id` INTEGER,\n'
                                   '        PRIMARY KEY (`item_id`)\n'
                                   '    )',
          'unit_reinforce_item_target_unit_m': 'CREATE TABLE `unit_reinforce_item_target_unit_m` (\n'
                                               '        `item_id` INTEGER NOT NULL,\n'
                                               '        `unit_id` INTEGER NOT NULL,\n'
                                               '        PRIMARY KEY (`item_id`,`unit_id`)\n'
                                               '    )',
          'user_rank_up_item_m': 'CREATE TABLE `user_rank_up_item_m` (\n'
                                 '        `item_id` INTEGER NOT NULL,\n'
                                 '        `use_limit_rank` INTEGER,\n'
                                 '        `use_limit_rank_min` INTEGER,\n'
                                 '        PRIMARY KEY (`item_id`)\n'
                                 '    )'},
 'live': {'free_live_m': 'CREATE TABLE `free_live_m` (\n'
                         '        `live_difficulty_id` INTEGER NOT NULL,\n'
                         '        `live_setting_id` INTEGER NOT NULL,\n'
                         '        `random_flag` INTEGER NOT NULL,\n'
                         '        PRIMARY KEY (`live_difficulty_id`)\n'
                         '    )',
          'live_combo_m': 'CREATE TABLE `live_combo_m` (\n'
                          '        `combo_cnt` INTEGER NOT NULL,\n'
                          '        `score_rate` REAL NOT NULL,\n'
                          '        `add_love_cnt` INTEGER NOT NULL,\n'
                          '        PRIMARY KEY (`combo_cnt`)\n'
                          '    )',
          'live_cutin_brightness_m': 'CREATE TABLE `live_cutin_brightness_m` (\n'
                                     '        `live_cutin_brightness_id` INTEGER NOT NULL,\n'
                                     '        `brightness` INTEGER NOT NULL,\n'
                                     '        PRIMARY KEY (`live_cutin_brightness_id`)\n'
                                     '    )',
          'live_goal_reward_common_m': 'CREATE TABLE `live_goal_reward_common_m` (\n'
                                       '        `live_goal_reward_common_id` INTEGER NOT NULL,\n'
                                       '        `live_type` INTEGER NOT NULL,\n'
                                       '        `difficulty` INTEGER NOT NULL,\n'
                                       '        `live_goal_type` INTEGER NOT NULL,\n'
                                       '        `rank` INTEGER NOT NULL,\n'
                                       '        `add_type` INTEGER NOT NULL,\n'
                                       '        `item_id` INTEGER NOT NULL,\n'
                                       '        `item_category_id` INTEGER,\n'
                                       '        `amount` INTEGER NOT NULL,\n'
                                       '        `item_option` TEXT,\n'
                                       '        PRIMARY KEY (`live_goal_reward_common_id`)\n'
                                       '    )',
          'live_goal_reward_m': 'CREATE TABLE `live_goal_reward_m` (\n'
                                '        `live_goal_reward_id` INTEGER NOT NULL,\n'
                                '        `live_difficulty_id` INTEGER NOT NULL,\n'
                                '        `live_goal_type` INTEGER NOT NULL,\n'
                                '        `rank` INTEGER NOT NULL,\n'
                                '        `add_type` INTEGER NOT NULL,\n'
                                '        `item_id` INTEGER NOT NULL,\n'
                                '        `item_category_id` INTEGER,\n'
                                '        `amount` INTEGER NOT NULL,\n'
                                '        `item_option` TEXT,\n'
                                '        PRIMARY KEY (`live_goal_reward_id`)\n'
                                '    )',
          'live_note_score_factor_m': 'CREATE TABLE `live_note_score_factor_m` (\n'
                                      '        `effect_id` INTEGER NOT NULL,\n'
                                      '        `difficulty` INTEGER NOT NULL,\n'
                                      '        `score_factor` REAL NOT NULL,\n'
                                      '        PRIMARY KEY (`effect_id`,`difficulty`)\n'
                                      '    )',
          'live_setting_m': 'CREATE TABLE `live_setting_m` (\n'
                            '        `live_setting_id` INTEGER NOT NULL,\n'
                            '        `live_track_id` INTEGER NOT NULL,\n'
                            '        `difficulty` INTEGER NOT NULL,\n'
                            '        `stage_level` INTEGER NOT NULL,\n'
                            '        `attribute_icon_id` INTEGER NOT NULL,\n'
                            '        `live_icon_asset` TEXT NOT NULL,\n'
                            '        `live_icon_asset_en` TEXT,\n'
                            '        `asset_movie_id` INTEGER,\n'
                            '        `asset_background_id` INTEGER NOT NULL,\n'
                            '        `notes_setting_asset` TEXT NOT NULL,\n'
                            '        `notes_setting_asset_en` TEXT,\n'
                            '        `c_rank_score` INTEGER NOT NULL,\n'
                            '        `b_rank_score` INTEGER NOT NULL,\n'
                            '        `a_rank_score` INTEGER NOT NULL,\n'
                            '        `s_rank_score` INTEGER NOT NULL,\n'
                            '        `c_rank_combo` INTEGER NOT NULL,\n'
                            '        `b_rank_combo` INTEGER NOT NULL,\n'
                            '        `a_rank_combo` INTEGER NOT NULL,\n'
                            '        `s_rank_combo` INTEGER NOT NULL,\n'
                            '        `ac_flag` INTEGER NOT NULL,\n'
                            '        `swing_flag` INTEGER NOT NULL,\n'
                            '        `lane_count` INTEGER NOT NULL,\n'
                            '        PRIMARY KEY (`live_setting_id`)\n'
                            '    )',
          'live_skill_icon_m': 'CREATE TABLE `live_skill_icon_m` (\n'
                               '        `skill_effect_type` INTEGER NOT NULL,\n'
                               '        `icon_asset` TEXT NOT NULL,\n'
                               '        `icon_asset_en` TEXT,\n'
                               '        `icon_order` INTEGER NOT NULL,\n'
                               '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                               '        PRIMARY KEY (`skill_effect_type`)\n'
                               '    )',
          'live_time_m': 'CREATE TABLE `live_time_m` (\n'
                         '        `live_track_id` INTEGER NOT NULL,\n'
                         '        `live_time` REAL NOT NULL,\n'
                         '        PRIMARY KEY (`live_track_id`)\n'
                         '    )',
          'live_track_m': 'CREATE TABLE `live_track_m` (\n'
                          '        `live_track_id` INTEGER NOT NULL,\n'
                          '        `name` TEXT NOT NULL,\n'
                          '        `name_en` TEXT,\n'
                          '        `name_kana` TEXT NOT NULL,\n'
                          '        `name_kana_en` TEXT,\n'
                          '        `title_asset` TEXT NOT NULL,\n'
                          '        `title_asset_en` TEXT,\n'
                          '        `sound_asset` TEXT NOT NULL,\n'
                          '        `member_category` INTEGER NOT NULL,\n'
                          '        `member_tag_id` INTEGER NOT NULL,\n'
                          '        `unit_type_id` INTEGER,\n'
                          '        PRIMARY KEY (`live_track_id`)\n'
                          '    )',
          'live_unit_reward_lot_m': 'CREATE TABLE `live_unit_reward_lot_m` (\n'
                                    '        `live_unit_reward_lot_id` INTEGER NOT NULL,\n'
                                    '        `difficulty` INTEGER NOT NULL,\n'
                                    '        `condition_type` INTEGER NOT NULL,\n'
                                    '        `rank` INTEGER,\n'
                                    '        `live_unit_reward_group_id` INTEGER NOT NULL,\n'
                                    '        `weight` INTEGER NOT NULL,\n'
                                    '        PRIMARY KEY (`live_unit_reward_lot_id`)\n'
                                    '    )',
          'normal_live_m': 'CREATE TABLE `normal_live_m` (\n'
                           '        `live_difficulty_id` INTEGER NOT NULL,\n'
                           '        `live_setting_id` INTEGER NOT NULL,\n'
                           '        `capital_type` INTEGER NOT NULL,\n'
                           '        `capital_value` INTEGER NOT NULL,\n'
                           '        `default_unlocked_flag` INTEGER NOT NULL,\n'
                           '        `c_rank_complete` INTEGER NOT NULL,\n'
                           '        `b_rank_complete` INTEGER NOT NULL,\n'
                           '        `a_rank_complete` INTEGER NOT NULL,\n'
                           '        `s_rank_complete` INTEGER NOT NULL,\n'
                           '        PRIMARY KEY (`live_difficulty_id`)\n'
                           '    )',
          'special_live_m': 'CREATE TABLE `special_live_m` (\n'
                            '        `live_difficulty_id` INTEGER NOT NULL,\n'
                            '        `live_setting_id` INTEGER NOT NULL,\n'
                            '        `capital_type` INTEGER NOT NULL,\n'
                            '        `capital_value` INTEGER NOT NULL,\n'
                            '        `c_rank_complete` INTEGER NOT NULL,\n'
                            '        `b_rank_complete` INTEGER NOT NULL,\n'
                            '        `a_rank_complete` INTEGER NOT NULL,\n'
                            '        `s_rank_complete` INTEGER NOT NULL,\n'
                            '        `exclude_clear_count_flag` INTEGER NOT NULL,\n'
                            '        `exclude_effort_point_flag` INTEGER NOT NULL,\n'
                            '        `exclude_live_bonus_flag` INTEGER NOT NULL,\n'
                            '        PRIMARY KEY (`live_difficulty_id`)\n'
                            '    )',
          'special_live_rotation_m': 'CREATE TABLE `special_live_rotation_m` (\n'
                                     '        `rotation_group_id` INTEGER NOT NULL,\n'
                                     '        `live_difficulty_id` INTEGER NOT NULL,\n'
                                     '        `base_date` TEXT NOT NULL,\n'
                                     '        PRIMARY KEY (`rotation_group_id`,`base_date`)\n'
                                     '    )',
          'training_mode_m': 'CREATE TABLE `training_mode_m` (\n'
                             '        `training_mode_id` INTEGER NOT NULL,\n'
                             '        `recovery_cost` INTEGER NOT NULL,\n'
                             '        `start_date` TEXT NOT NULL,\n'
                             '        PRIMARY KEY (`training_mode_id`)\n'
                             '    )'},
 'museum': {'museum_contents_m': 'CREATE TABLE `museum_contents_m` (\n'
                                 '        `museum_contents_id` INTEGER NOT NULL,\n'
                                 '        `museum_tab_category_id` INTEGER NOT NULL,\n'
                                 '        `master_id` INTEGER,\n'
                                 '        `thumbnail_asset` TEXT,\n'
                                 '        `thumbnail_asset_en` TEXT,\n'
                                 '        `title` TEXT NOT NULL,\n'
                                 '        `title_en` TEXT,\n'
                                 '        `category` TEXT NOT NULL,\n'
                                 '        `category_en` TEXT,\n'
                                 '        `museum_rarity` INTEGER NOT NULL,\n'
                                 '        `attribute_id` INTEGER NOT NULL,\n'
                                 '        `smile_buff` INTEGER NOT NULL,\n'
                                 '        `pure_buff` INTEGER NOT NULL,\n'
                                 '        `cool_buff` INTEGER NOT NULL,\n'
                                 '        `sort_id` INTEGER NOT NULL,\n'
                                 '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                 '        PRIMARY KEY (`museum_contents_id`)\n'
                                 '    )'},
 'scenario': {'scenario_chapter_m': 'CREATE TABLE `scenario_chapter_m` (\n'
                                    '        `scenario_chapter_id` INTEGER NOT NULL,\n'
                                    '        `name` TEXT NOT NULL,\n'
                                    '        `name_en` TEXT,\n'
                                    '        `outline` TEXT,\n'
                                    '        `outline_en` TEXT,\n'
                                    '        `image_asset` TEXT,\n'
                                    '        `image_asset_en` TEXT,\n'
                                    '        `type` INTEGER NOT NULL,\n'
                                    '        `sort` INTEGER,\n'
                                    '        `member_category` INTEGER NOT NULL,\n'
                                    '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                    '        PRIMARY KEY (`scenario_chapter_id`)\n'
                                    '    )',
              'scenario_m': 'CREATE TABLE `scenario_m` (\n'
                            '        `scenario_id` INTEGER NOT NULL,\n'
                            '        `scenario_chapter_id` INTEGER NOT NULL,\n'
                            '        `title` TEXT NOT NULL,\n'
                            '        `title_en` TEXT,\n'
                            '        `title_call_asset` TEXT,\n'
                            '        `title_call_asset_en` TEXT,\n'
                            '        `title_font` INTEGER,\n'
                            '        `outline` TEXT,\n'
                            '        `outline_en` TEXT,\n'
                            '        `asset_bgm_id` INTEGER NOT NULL,\n'
                            '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                            '        PRIMARY KEY (`scenario_id`)\n'
                            '    )'},
 'subscenario': {'subscenario_m': 'CREATE TABLE `subscenario_m` (\n'
                                  '        `subscenario_id` INTEGER NOT NULL,\n'
                                  '        `unit_id` INTEGER NOT NULL,\n'
                                  '        `title` TEXT NOT NULL,\n'
                                  '        `title_en` TEXT,\n'
                                  '        `asset_bgm_id` INTEGER NOT NULL,\n'
                                  '        `scenario_char_asset_id` INTEGER,\n'
                                  '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                  '        PRIMARY KEY (`subscenario_id`)\n'
                                  '    )'},
 'unit': {'accessory_base_setting_m': 'CREATE TABLE `accessory_base_setting_m` (\n'
                                      '        `accessory_base_setting_id` INTEGER NOT NULL,\n'
                                      '        `owning_capacity` INTEGER NOT NULL,\n'
                                      '        `owning_material_capacity` INTEGER NOT NULL,\n'
                                      '        PRIMARY KEY (`accessory_base_setting_id`)\n'
                                      '    )',
          'accessory_level_limit_over_m': 'CREATE TABLE `accessory_level_limit_over_m` (\n'
                                          '        `base_rarity` INTEGER NOT NULL,\n'
                                          '        `material_rarity` INTEGER NOT NULL,\n'
                                          '        `amount` INTEGER NOT NULL,\n'
                                          '        PRIMARY KEY (`base_rarity`,`material_rarity`)\n'
                                          '    )',
          'accessory_level_m': 'CREATE TABLE `accessory_level_m` (\n'
                               '        `accessory_id` INTEGER NOT NULL,\n'
                               '        `level` INTEGER NOT NULL,\n'
                               '        `next_exp` INTEGER NOT NULL,\n'
                               '        `effect_range` INTEGER,\n'
                               '        `effect_value` REAL,\n'
                               '        `discharge_time` REAL,\n'
                               '        `trigger_value` INTEGER,\n'
                               '        `activation_rate` INTEGER,\n'
                               '        `unit_skill_combo_pattern_id` INTEGER,\n'
                               '        `spark_count_limit` INTEGER,\n'
                               '        `smile_diff` INTEGER NOT NULL,\n'
                               '        `pure_diff` INTEGER NOT NULL,\n'
                               '        `cool_diff` INTEGER NOT NULL,\n'
                               '        `grant_exp` INTEGER NOT NULL,\n'
                               '        `merge_cost` INTEGER NOT NULL,\n'
                               '        `sale_price` INTEGER NOT NULL,\n'
                               '        PRIMARY KEY (`accessory_id`,`level`)\n'
                               '    )',
          'accessory_lottery_cost_m': 'CREATE TABLE `accessory_lottery_cost_m` (\n'
                                      '        `accessory_lottery_cost_id` INTEGER NOT NULL,\n'
                                      '        `status_type` INTEGER NOT NULL,\n'
                                      '        `from_value` INTEGER NOT NULL,\n'
                                      '        `to_value` INTEGER NOT NULL,\n'
                                      '        `cost_value` INTEGER NOT NULL,\n'
                                      '        PRIMARY KEY (`accessory_lottery_cost_id`)\n'
                                      '    )',
          'accessory_lottery_group_m': 'CREATE TABLE `accessory_lottery_group_m` (\n'
                                       '        `accessory_lottery_group_id` INTEGER NOT NULL,\n'
                                       '        `from_cost` INTEGER NOT NULL,\n'
                                       '        `to_cost` INTEGER NOT NULL,\n'
                                       '        PRIMARY KEY (`accessory_lottery_group_id`)\n'
                                       '    )',
          'accessory_lottery_list_m': 'CREATE TABLE `accessory_lottery_list_m` (\n'
                                      '        `accessory_lottery_list_id` INTEGER NOT NULL,\n'
                                      '        `accessory_lottery_group_id` INTEGER NOT NULL,\n'
                                      '        `accessory_id` INTEGER NOT NULL,\n'
                                      '        `weight` INTEGER NOT NULL,\n'
                                      '        `start_date` TEXT,\n'
                                      '        `end_date` TEXT,\n'
                                      '        PRIMARY KEY (`accessory_lottery_list_id`)\n'
                                      '    )',
          'accessory_m': 'CREATE TABLE `accessory_m` (\n'
                         '        `accessory_id` INTEGER NOT NULL,\n'
                         '        `name` TEXT NOT NULL,\n'
                         '        `name_en` TEXT,\n'
                         '        `rarity` INTEGER NOT NULL,\n'
                         '        `smile_max` INTEGER NOT NULL,\n'
                         '        `pure_max` INTEGER NOT NULL,\n'
                         '        `cool_max` INTEGER NOT NULL,\n'
                         '        `is_material` INTEGER NOT NULL,\n'
                         '        `effect_type` INTEGER,\n'
                         '        `default_max_level` INTEGER NOT NULL,\n'
                         '        `max_level` INTEGER NOT NULL,\n'
                         '        `accessory_asset_id` INTEGER NOT NULL,\n'
                         '        `trigger_type` INTEGER,\n'
                         '        `trigger_effect_type` INTEGER,\n'
                         '        `open_date` TEXT,\n'
                         '        PRIMARY KEY (`accessory_id`)\n'
                         '    )',
          'accessory_special_m': 'CREATE TABLE `accessory_special_m` (\n'
                                 '        `accessory_id` INTEGER NOT NULL,\n'
                                 '        `unit_id` INTEGER NOT NULL,\n'
                                 '        PRIMARY KEY (`accessory_id`,`unit_id`)\n'
                                 '    )',
          'album_series_m': 'CREATE TABLE `album_series_m` (\n'
                            '        `album_series_id` INTEGER NOT NULL,\n'
                            '        `album_group_id` INTEGER NOT NULL,\n'
                            '        `album_tab_id` INTEGER NOT NULL,\n'
                            '        `order_num` INTEGER NOT NULL,\n'
                            '        `name` TEXT,\n'
                            '        `name_en` TEXT,\n'
                            '        `layout_type` INTEGER NOT NULL,\n'
                            '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                            '        PRIMARY KEY (`album_series_id`)\n'
                            '    )',
          'member_tag_m': 'CREATE TABLE `member_tag_m` (\n'
                          '        `member_tag_id` INTEGER NOT NULL,\n'
                          '        `name` TEXT NOT NULL,\n'
                          '        `name_en` TEXT,\n'
                          '        `img_asset` TEXT,\n'
                          '        `img_asset_en` TEXT,\n'
                          '        `display_flag` INTEGER NOT NULL,\n'
                          '        `num_of_members` INTEGER,\n'
                          '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                          '        PRIMARY KEY (`member_tag_id`)\n'
                          '    )',
          'unit_attribute_m': 'CREATE TABLE `unit_attribute_m` (\n'
                              '        `attribute_id` INTEGER NOT NULL,\n'
                              '        `name` TEXT NOT NULL,\n'
                              '        `name_en` TEXT,\n'
                              '        PRIMARY KEY (`attribute_id`)\n'
                              '    )',
          'unit_base_function_voice_m': 'CREATE TABLE `unit_base_function_voice_m` (\n'
                                        '        `unit_base_function_voice_id` INTEGER NOT NULL,\n'
                                        '        `unit_type_id` INTEGER NOT NULL,\n'
                                        '        `unit_status` INTEGER NOT NULL,\n'
                                        '        `function_id` INTEGER NOT NULL,\n'
                                        '        `function_type` INTEGER NOT NULL,\n'
                                        '        `asset_voice_id` INTEGER NOT NULL,\n'
                                        '        `weight` INTEGER NOT NULL,\n'
                                        '        PRIMARY KEY (`unit_base_function_voice_id`)\n'
                                        '    )',
          'unit_base_random_voice_m': 'CREATE TABLE `unit_base_random_voice_m` (\n'
                                      '        `unit_base_random_voice_id` INTEGER NOT NULL,\n'
                                      '        `unit_type_id` INTEGER NOT NULL,\n'
                                      '        `unit_status` INTEGER NOT NULL,\n'
                                      '        `asset_voice_id` INTEGER NOT NULL,\n'
                                      '        `weight` INTEGER NOT NULL,\n'
                                      '        PRIMARY KEY (`unit_base_random_voice_id`)\n'
                                      '    )',
          'unit_base_touch_voice_m': 'CREATE TABLE `unit_base_touch_voice_m` (\n'
                                     '        `unit_base_touch_voice_id` INTEGER NOT NULL,\n'
                                     '        `unit_type_id` INTEGER NOT NULL,\n'
                                     '        `unit_status` INTEGER NOT NULL,\n'
                                     '        `from_x` INTEGER NOT NULL,\n'
                                     '        `from_y` INTEGER NOT NULL,\n'
                                     '        `to_x` INTEGER NOT NULL,\n'
                                     '        `to_y` INTEGER NOT NULL,\n'
                                     '        `asset_voice_id` INTEGER NOT NULL,\n'
                                     '        `weight` INTEGER NOT NULL,\n'
                                     '        `min_rarity` INTEGER NOT NULL,\n'
                                     '        PRIMARY KEY (`unit_base_touch_voice_id`)\n'
                                     '    )',
          'unit_function_voice_m': 'CREATE TABLE `unit_function_voice_m` (\n'
                                   '        `unit_function_voice_id` INTEGER NOT NULL,\n'
                                   '        `unit_id` INTEGER NOT NULL,\n'
                                   '        `unit_status` INTEGER NOT NULL,\n'
                                   '        `function_id` INTEGER NOT NULL,\n'
                                   '        `function_type` INTEGER NOT NULL,\n'
                                   '        `asset_voice_id` INTEGER NOT NULL,\n'
                                   '        `weight` INTEGER NOT NULL,\n'
                                   '        PRIMARY KEY (`unit_function_voice_id`)\n'
                                   '    )',
          'unit_leader_skill_extra_m': 'CREATE TABLE `unit_leader_skill_extra_m` (\n'
                                       '        `unit_leader_skill_id` INTEGER NOT NULL,\n'
                                       '        `member_tag_id` INTEGER NOT NULL,\n'
                                       '        `leader_skill_effect_type` INTEGER NOT NULL,\n'
                                       '        `effect_value` INTEGER NOT NULL,\n'
                                       '        PRIMARY KEY (`unit_leader_skill_id`)\n'
                                       '    )',
          'unit_leader_skill_m': 'CREATE TABLE `unit_leader_skill_m` (\n'
                                 '        `unit_leader_skill_id` INTEGER NOT NULL,\n'
                                 '        `leader_skill_effect_type` INTEGER NOT NULL,\n'
                                 '        `effect_value` INTEGER NOT NULL,\n'
                                 '        `name_string_key` TEXT,\n'
                                 '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                 '        PRIMARY KEY (`unit_leader_skill_id`)\n'
                                 '    )',
          'unit_level_limit_pattern_m': 'CREATE TABLE `unit_level_limit_pattern_m` (\n'
                                        '        `unit_level_limit_id` INTEGER NOT NULL,\n'
                                        '        `unit_level` INTEGER NOT NULL,\n'
                                        '        `next_exp` INTEGER NOT NULL,\n'
                                        '        `hp_diff` INTEGER NOT NULL,\n'
                                        '        `smile_diff` INTEGER NOT NULL,\n'
                                        '        `pure_diff` INTEGER NOT NULL,\n'
                                        '        `cool_diff` INTEGER NOT NULL,\n'
                                        '        `merge_exp` INTEGER NOT NULL,\n'
                                        '        `merge_cost` INTEGER NOT NULL,\n'
                                        '        `sale_price` INTEGER NOT NULL,\n'
                                        '        PRIMARY KEY (`unit_level_limit_id`,`unit_level`)\n'
                                        '    )',
          'unit_level_up_pattern_m': 'CREATE TABLE `unit_level_up_pattern_m` (\n'
                                     '        `unit_level_up_pattern_id` INTEGER NOT NULL,\n'
                                     '        `unit_level` INTEGER NOT NULL,\n'
                                     '        `next_exp` INTEGER NOT NULL,\n'
                                     '        `hp_diff` INTEGER NOT NULL,\n'
                                     '        `smile_diff` INTEGER NOT NULL,\n'
                                     '        `pure_diff` INTEGER NOT NULL,\n'
                                     '        `cool_diff` INTEGER NOT NULL,\n'
                                     '        `merge_exp` INTEGER NOT NULL,\n'
                                     '        `merge_cost` INTEGER NOT NULL,\n'
                                     '        `sale_price` INTEGER NOT NULL,\n'
                                     '        PRIMARY KEY (`unit_level_up_pattern_id`,`unit_level`)\n'
                                     '    )',
          'unit_m': 'CREATE TABLE `unit_m` (\n'
                    '        `unit_id` INTEGER NOT NULL,\n'
                    '        `unit_number` INTEGER NOT NULL,\n'
                    '        `unit_type_id` INTEGER NOT NULL,\n'
                    '        `album_series_id` INTEGER,\n'
                    '        `eponym` TEXT,\n'
                    '        `eponym_en` TEXT,\n'
                    '        `name` TEXT NOT NULL,\n'
                    '        `name_en` TEXT,\n'
                    '        `normal_card_id` INTEGER NOT NULL,\n'
                    '        `rank_max_card_id` INTEGER NOT NULL,\n'
                    '        `normal_icon_asset` TEXT NOT NULL,\n'
                    '        `normal_icon_asset_en` TEXT,\n'
                    '        `rank_max_icon_asset` TEXT NOT NULL,\n'
                    '        `rank_max_icon_asset_en` TEXT,\n'
                    '        `normal_unit_navi_asset_id` INTEGER NOT NULL,\n'
                    '        `rank_max_unit_navi_asset_id` INTEGER NOT NULL,\n'
                    '        `rarity` INTEGER NOT NULL,\n'
                    '        `attribute_id` INTEGER NOT NULL,\n'
                    '        `default_unit_skill_id` INTEGER,\n'
                    '        `skill_asset_voice_id` INTEGER,\n'
                    '        `default_leader_skill_id` INTEGER,\n'
                    '        `default_removable_skill_capacity` INTEGER NOT NULL,\n'
                    '        `max_removable_skill_capacity` INTEGER NOT NULL,\n'
                    '        `disable_rank_up` INTEGER NOT NULL,\n'
                    '        `rank_min` INTEGER NOT NULL,\n'
                    '        `rank_max` INTEGER NOT NULL,\n'
                    '        `unit_level_up_pattern_id` INTEGER NOT NULL,\n'
                    '        `hp_max` INTEGER NOT NULL,\n'
                    '        `smile_max` INTEGER NOT NULL,\n'
                    '        `pure_max` INTEGER NOT NULL,\n'
                    '        `cool_max` INTEGER NOT NULL,\n'
                    '        `reinforce_item_rank_up_cost` INTEGER,\n'
                    '        `sub_unit_type_id` INTEGER,\n'
                    '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                    '        PRIMARY KEY (`unit_id`)\n'
                    '    )',
          'unit_member_tag_m': 'CREATE TABLE `unit_member_tag_m` (\n'
                               '        `unit_id` INTEGER NOT NULL,\n'
                               '        `member_tag_id` INTEGER NOT NULL,\n'
                               '        PRIMARY KEY (`unit_id`,`member_tag_id`)\n'
                               '    )',
          'unit_random_voice_m': 'CREATE TABLE `unit_random_voice_m` (\n'
                                 '        `unit_random_voice_id` INTEGER NOT NULL,\n'
                                 '        `unit_id` INTEGER NOT NULL,\n'
                                 '        `unit_status` INTEGER NOT NULL,\n'
                                 '        `asset_voice_id` INTEGER NOT NULL,\n'
                                 '        `weight` INTEGER NOT NULL,\n'
                                 '        PRIMARY KEY (`unit_random_voice_id`)\n'
                                 '    )',
          'unit_rarity_m': 'CREATE TABLE `unit_rarity_m` (\n'
                           '        `rarity` INTEGER NOT NULL,\n'
                           '        `before_love_max` INTEGER NOT NULL,\n'
                           '        `after_love_max` INTEGER NOT NULL,\n'
                           '        `before_level_max` INTEGER NOT NULL,\n'
                           '        `after_level_max` INTEGER NOT NULL,\n'
                           '        `rank_up_cost` INTEGER NOT NULL,\n'
                           '        `exchange_point_rank_up_cost` INTEGER NOT NULL,\n'
                           '        `sort` INTEGER NOT NULL,\n'
                           '        `costume_level_limit` INTEGER NOT NULL,\n'
                           '        PRIMARY KEY (`rarity`)\n'
                           '    )',
          'unit_removable_skill_m': 'CREATE TABLE `unit_removable_skill_m` (\n'
                                    '        `unit_removable_skill_id` INTEGER NOT NULL,\n'
                                    '        `name` TEXT NOT NULL,\n'
                                    '        `name_en` TEXT,\n'
                                    '        `skill_type` INTEGER NOT NULL,\n'
                                    '        `unit_rarity` INTEGER,\n'
                                    '        `level` INTEGER NOT NULL,\n'
                                    '        `icon_asset` TEXT NOT NULL,\n'
                                    '        `icon_asset_en` TEXT,\n'
                                    '        `small_icon_asset` TEXT,\n'
                                    '        `small_icon_asset_en` TEXT,\n'
                                    '        `middle_icon_asset` TEXT,\n'
                                    '        `middle_icon_asset_en` TEXT,\n'
                                    '        `bond_asset` TEXT NOT NULL,\n'
                                    '        `bond_asset_en` TEXT,\n'
                                    '        `size` INTEGER NOT NULL,\n'
                                    '        `description` TEXT,\n'
                                    '        `description_en` TEXT,\n'
                                    '        `effect_range` INTEGER NOT NULL,\n'
                                    '        `effect_type` INTEGER NOT NULL,\n'
                                    '        `effect_value` REAL NOT NULL,\n'
                                    '        `fixed_value_flag` INTEGER NOT NULL,\n'
                                    '        `target_reference_type` INTEGER NOT NULL,\n'
                                    '        `target_type` INTEGER NOT NULL,\n'
                                    '        `trigger_reference_type` INTEGER NOT NULL,\n'
                                    '        `trigger_type` INTEGER NOT NULL,\n'
                                    '        `sub_skill_id` INTEGER,\n'
                                    '        `selling_price` INTEGER NOT NULL,\n'
                                    '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                    '        PRIMARY KEY (`unit_removable_skill_id`)\n'
                                    '    )',
          'unit_sign_asset_m': 'CREATE TABLE `unit_sign_asset_m` (\n'
                               '        `unit_id` INTEGER NOT NULL,\n'
                               '        `normal_card_id` INTEGER NOT NULL,\n'
                               '        `rank_max_card_id` INTEGER NOT NULL,\n'
                               '        `normal_icon_asset` TEXT NOT NULL,\n'
                               '        `normal_icon_asset_en` TEXT,\n'
                               '        `rank_max_icon_asset` TEXT NOT NULL,\n'
                               '        `rank_max_icon_asset_en` TEXT,\n'
                               '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                               '        PRIMARY KEY (`unit_id`)\n'
                               '    )',
          'unit_skill_level_m': 'CREATE TABLE `unit_skill_level_m` (\n'
                                '        `unit_skill_id` INTEGER NOT NULL,\n'
                                '        `skill_level` INTEGER NOT NULL,\n'
                                '        `effect_range` INTEGER,\n'
                                '        `effect_value` REAL NOT NULL,\n'
                                '        `discharge_time` REAL NOT NULL,\n'
                                '        `trigger_value` INTEGER NOT NULL,\n'
                                '        `trigger_limit` INTEGER,\n'
                                '        `activation_rate` INTEGER NOT NULL,\n'
                                '        `unit_skill_combo_pattern_id` INTEGER,\n'
                                '        `spark_count_limit` INTEGER,\n'
                                '        `grant_exp` INTEGER NOT NULL,\n'
                                '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                                '        PRIMARY KEY (`unit_skill_id`,`skill_level`)\n'
                                '    )',
          'unit_skill_level_up_pattern_m': 'CREATE TABLE `unit_skill_level_up_pattern_m` (\n'
                                           '        `unit_skill_level_up_pattern_id` INTEGER NOT NULL,\n'
                                           '        `skill_level` INTEGER NOT NULL,\n'
                                           '        `next_exp` INTEGER NOT NULL,\n'
                                           '        PRIMARY KEY (`unit_skill_level_up_pattern_id`,`skill_level`)\n'
                                           '    )',
          'unit_skill_m': 'CREATE TABLE `unit_skill_m` (\n'
                          '        `unit_skill_id` INTEGER NOT NULL,\n'
                          '        `name` TEXT NOT NULL,\n'
                          '        `name_en` TEXT,\n'
                          '        `max_level` INTEGER NOT NULL,\n'
                          '        `skill_effect_type` INTEGER NOT NULL,\n'
                          '        `discharge_type` INTEGER NOT NULL,\n'
                          '        `trigger_type` INTEGER NOT NULL,\n'
                          '        `trigger_effect_type` INTEGER,\n'
                          '        `unit_skill_level_up_pattern_id` INTEGER NOT NULL,\n'
                          '        `string_key_trigger` TEXT,\n'
                          '        `string_key_effect` TEXT,\n'
                          '        `string_key_long_description` TEXT,\n'
                          '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                          '        PRIMARY KEY (`unit_skill_id`)\n'
                          '    )',
          'unit_touch_voice_m': 'CREATE TABLE `unit_touch_voice_m` (\n'
                                '        `unit_touch_voice_id` INTEGER NOT NULL,\n'
                                '        `unit_id` INTEGER NOT NULL,\n'
                                '        `unit_status` INTEGER NOT NULL,\n'
                                '        `from_x` INTEGER NOT NULL,\n'
                                '        `from_y` INTEGER NOT NULL,\n'
                                '        `to_x` INTEGER NOT NULL,\n'
                                '        `to_y` INTEGER NOT NULL,\n'
                                '        `asset_voice_id` INTEGER NOT NULL,\n'
                                '        `weight` INTEGER NOT NULL,\n'
                                '        PRIMARY KEY (`unit_touch_voice_id`)\n'
                                '    )',
          'unit_type_m': 'CREATE TABLE `unit_type_m` (\n'
                         '        `unit_type_id` INTEGER NOT NULL,\n'
                         '        `name` TEXT NOT NULL,\n'
                         '        `name_en` TEXT,\n'
                         '        `speaker_name` TEXT NOT NULL,\n'
                         '        `speaker_name_en` TEXT,\n'
                         '        `asset_background_id` INTEGER,\n'
                         '        `image_button_asset` TEXT,\n'
                         '        `image_button_asset_en` TEXT,\n'
                         '        `background_color` TEXT NOT NULL,\n'
                         '        `background_color_en` TEXT,\n'
                         '        `name_image_asset` TEXT,\n'
                         '        `name_image_asset_en` TEXT,\n'
                         '        `album_series_name_image_asset` TEXT,\n'
                         '        `album_series_name_image_asset_en` TEXT,\n'
                         '        `skit_icon_asset` TEXT,\n'
                         '        `named_skit_icon_asset` TEXT,\n'
                         '        `named_skit_icon_asset_en` TEXT,\n'
                         '        `name_plate_icon_asset` TEXT,\n'
                         '        `age` TEXT NOT NULL,\n'
                         '        `age_en` TEXT,\n'
                         '        `birthday` TEXT,\n'
                         '        `birthday_en` TEXT,\n'
                         '        `school` TEXT,\n'
                         '        `school_en` TEXT,\n'
                         '        `hobby` TEXT,\n'
                         '        `hobby_en` TEXT,\n'
                         '        `blood_type` TEXT,\n'
                         '        `blood_type_en` TEXT,\n'
                         '        `height` TEXT,\n'
                         '        `height_en` TEXT,\n'
                         '        `three_size` TEXT,\n'
                         '        `three_size_en` TEXT,\n'
                         '        `member_category` INTEGER NOT NULL,\n'
                         '        `cv` TEXT,\n'
                         '        `cv_en` TEXT,\n'
                         '        `original_attribute_id` INTEGER,\n'
                         '        `release_tag` TEXT, `_encryption_release_id` INTEGER NULL,\n'
                         '        PRIMARY KEY (`unit_type_id`)\n'
                         '    )',
          'unit_type_member_tag_m': 'CREATE TABLE `unit_type_member_tag_m` (\n'
                                    '        `unit_type_id` INTEGER NOT NULL,\n'
                                    '        `member_tag_id` INTEGER NOT NULL,\n'
                                    '        PRIMARY KEY (`unit_type_id`,`member_tag_id`)\n'
                                    '    )'}}
