#!/usr/bin/env python3
"""Safely migrate an upstream/vanilla NPPS4 deployment into NPPS4 v5.32.

Standard-library only. The script:
  * creates timestamped backups;
  * migrates a SQLite player database using SQLite's online backup API;
  * rewrites the old single-profile config into the v5.32 CN/GL profile layout;
  * performs a keyed three-way merge of server_data.json so v5.32 additions
    (Chinese names, extra scouting pages, serial-code changes, etc.) survive;
  * optionally runs Alembic and NPPS4's post-migration fixes.

It does NOT silently migrate external PostgreSQL/MySQL databases. For those,
point v5.32 at the existing database and run Alembic from the v5.32 source.
"""
from __future__ import annotations

import argparse
import copy
import datetime as dt
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any
from urllib.parse import unquote

SCRIPT_DIR = Path(__file__).resolve().parent
VANILLA_SERVER_DATA_REFERENCE = SCRIPT_DIR / "vanilla_server_data_reference.json"

LIST_KEYS: dict[str, str] = {
    "achievement_reward": "achievement_id",
    "common_live_unit_drops": "unit_id",
    "live_specific_live_unit_drops": "live_setting_id",
    "live_effort_drops": "live_effort_point_box_spec_id",
    "secretbox_data": "id_string",
    "serial_codes": "serial_code",
    "sticker_shop": "id_string",
}


class MigrationError(RuntimeError):
    pass


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(toml_scalar(v) for v in value) + "]"
    raise TypeError(f"Unsupported TOML value: {type(value).__name__}")


def dump_toml(data: dict[str, Any]) -> str:
    """Serialize the subset of TOML used by NPPS4 config files."""
    lines: list[str] = [
        "# Generated by migrate_npps4_vanilla_to_v532.py",
        "# The original and target config files were backed up before this file was written.",
        "",
    ]

    def emit_table(table: dict[str, Any], path: tuple[str, ...]) -> None:
        scalar_items = [(k, v) for k, v in table.items() if not isinstance(v, dict)]
        child_items = [(k, v) for k, v in table.items() if isinstance(v, dict)]
        if path:
            lines.append("[" + ".".join(path) + "]")
        for key, value in scalar_items:
            lines.append(f"{key} = {toml_scalar(value)}")
        if path or scalar_items:
            lines.append("")
        for key, value in child_items:
            emit_table(value, path + (key,))

    root_scalars = {k: v for k, v in data.items() if not isinstance(v, dict)}
    for key, value in root_scalars.items():
        lines.append(f"{key} = {toml_scalar(value)}")
    if root_scalars:
        lines.append("")
    for key, value in data.items():
        if isinstance(value, dict):
            emit_table(value, (key,))
    return "\n".join(lines).rstrip() + "\n"


def deep_overlay(base: dict[str, Any], override: dict[str, Any], *, skip: set[str] | None = None) -> dict[str, Any]:
    result = copy.deepcopy(base)
    skip = skip or set()
    for key, value in override.items():
        if key in skip:
            continue
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_overlay(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def migrate_download_config(
    target_config: dict[str, Any], old_config: dict[str, Any], legacy_profile: str, preserve_other_profile: bool
) -> dict[str, Any]:
    result = deep_overlay(target_config, old_config, skip={"download", "compat"})
    target_download = copy.deepcopy(target_config.get("download", {}))
    old_download = copy.deepcopy(old_config.get("download", {}))

    profiles = target_download.setdefault("profiles", {})
    profiles.setdefault("cn", {})
    profiles.setdefault("gl", {})
    other = "cn" if legacy_profile == "gl" else "gl"

    backend = str(old_download.get("backend", "none") or "none").strip().lower()
    migrated = copy.deepcopy(profiles.get(legacy_profile, {}))
    migrated["enabled"] = True
    migrated["backend"] = backend
    migrated["send_patched_server_info"] = bool(
        old_download.get("send_patched_server_info", old_download.get("fixserverinfo", True))
    )
    for section in ("none", "n4dlapi", "internal", "cn_archive", "custom"):
        if section in old_download:
            migrated[section] = copy.deepcopy(old_download[section])
    profiles[legacy_profile] = migrated

    if not preserve_other_profile:
        profiles[other]["enabled"] = False
        profiles[other]["backend"] = profiles[other].get("backend", "")

    target_download["backend"] = ""
    target_download["default_profile"] = legacy_profile
    target_download["profiles"] = profiles
    result["download"] = target_download

    compat = copy.deepcopy(target_config.get("compat", {}))
    compat.update(old_config.get("compat", {}))
    compat["region"] = "dual"
    result["compat"] = compat
    result.setdefault("gameplay", {}).setdefault("museum_stat_bonus_enabled", False)
    return result


def detect_core_root(path: Path) -> Path:
    candidates = [
        path,
        path / "app" / "src" / "main" / "python",
    ]
    for candidate in candidates:
        if (candidate / "main.py").is_file() and (candidate / "npps4").is_dir():
            return candidate.resolve()
    raise MigrationError(
        f"Cannot find NPPS4 core root under {path}. Expected main.py and npps4/, "
        "or app/src/main/python/main.py."
    )


def find_config(root: Path, explicit: str | None, *, target: bool) -> Path:
    if explicit:
        path = Path(explicit).expanduser().resolve()
        if not path.is_file():
            raise MigrationError(f"Config file not found: {path}")
        return path
    direct = root / "config.toml"
    if direct.is_file():
        return direct
    sample = root / "config.sample.toml"
    if target and sample.is_file():
        return sample
    raise MigrationError(f"No {'config.toml or config.sample.toml' if target else 'config.toml'} found in {root}")


def sqlite_path_from_url(url: str, root: Path) -> Path | None:
    prefixes = ("sqlite+aiosqlite:///", "sqlite:///")
    prefix = next((p for p in prefixes if url.startswith(p)), None)
    if prefix is None:
        return None
    value = unquote(url[len(prefix):])
    # Windows absolute path in SQLAlchemy form: C:/foo or /C:/foo.
    if len(value) >= 3 and value[1] == ":" and value[2] in "/\\":
        return Path(value)
    if len(value) >= 4 and value[0] == "/" and value[2] == ":" and value[3] in "/\\":
        return Path(value[1:])
    path = Path(value)
    return path if path.is_absolute() else (root / path).resolve()


def sqlite_integrity(path: Path) -> None:
    if not path.is_file():
        raise MigrationError(f"SQLite database not found: {path}")
    con = sqlite3.connect(f"file:{path.as_posix()}?mode=ro", uri=True)
    try:
        row = con.execute("PRAGMA integrity_check").fetchone()
    finally:
        con.close()
    if not row or row[0] != "ok":
        raise MigrationError(f"SQLite integrity_check failed for {path}: {row}")


def sqlite_backup(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    src = sqlite3.connect(f"file:{source.as_posix()}?mode=ro", uri=True)
    dst = sqlite3.connect(destination)
    try:
        src.backup(dst)
    finally:
        dst.close()
        src.close()
    sqlite_integrity(destination)


def keyed_list_merge(section: str, base: list[Any], old: list[Any], target: list[Any], conflicts: list[str]) -> list[Any]:
    key_name = LIST_KEYS.get(section)
    if not key_name or not all(isinstance(x, dict) and key_name in x for x in base + old + target):
        if old == base:
            return copy.deepcopy(target)
        if target == base or old == target:
            return copy.deepcopy(old)
        conflicts.append(f"{section}: non-keyed list changed in both old and v5.32; kept v5.32 value")
        return copy.deepcopy(target)

    def freeze_key(value: Any) -> Any:
        if isinstance(value, dict):
            return ("dict", tuple(sorted((str(k), freeze_key(v)) for k, v in value.items())))
        if isinstance(value, list):
            return ("list", tuple(freeze_key(v) for v in value))
        return value

    def index(items: list[dict[str, Any]]) -> tuple[dict[Any, dict[str, Any]], list[Any]]:
        keys = [freeze_key(item[key_name]) for item in items]
        return ({key: item for key, item in zip(keys, items, strict=True)}, keys)

    bmap, border = index(base)
    omap, oorder = index(old)
    tmap, torder = index(target)
    result = copy.deepcopy(tmap)

    # Explicit removals relative to the exact vanilla reference.
    for key in set(bmap) - set(omap):
        result.pop(key, None)

    # Additions and modifications made by the old operator.
    for key in oorder:
        if key not in bmap:
            if key not in result:
                result[key] = copy.deepcopy(omap[key])
            elif result[key] != omap[key]:
                conflicts.append(f"{section}[{key!r}]: custom addition collides with v5.32; kept v5.32")
            continue
        if omap[key] != bmap[key]:
            if key in result:
                result[key] = three_way_merge(
                    bmap[key], omap[key], result[key], conflicts, f"{section}[{key!r}]"
                )
            else:
                result[key] = copy.deepcopy(omap[key])

    order = [key for key in torder if key in result]
    order.extend(key for key in oorder if key in result and key not in order)
    return [result[key] for key in order]


def three_way_merge(base: Any, old: Any, target: Any, conflicts: list[str], path: str = "root") -> Any:
    if old == base:
        return copy.deepcopy(target)
    if target == base or old == target:
        return copy.deepcopy(old)
    if isinstance(base, dict) and isinstance(old, dict) and isinstance(target, dict):
        result = copy.deepcopy(target)
        all_keys = set(base) | set(old) | set(target)
        for key in all_keys:
            child = f"{path}.{key}"
            if key not in old and key in base:
                result.pop(key, None)
            elif key not in base and key in old:
                if key not in target:
                    result[key] = copy.deepcopy(old[key])
                elif target[key] != old[key]:
                    conflicts.append(f"{child}: custom addition collides with v5.32; kept v5.32")
            elif key in old and key in base:
                if key in target:
                    result[key] = three_way_merge(base[key], old[key], target[key], conflicts, child)
                elif old[key] != base[key]:
                    result[key] = copy.deepcopy(old[key])
        return result
    if isinstance(base, list) and isinstance(old, list) and isinstance(target, list):
        section = path.split(".")[-1]
        return keyed_list_merge(section, base, old, target, conflicts)
    conflicts.append(f"{path}: changed in both old and v5.32; kept v5.32 value")
    return copy.deepcopy(target)


def copy_if_present(source: Path, destination: Path, backup_dir: Path, dry_run: bool) -> bool:
    if not source.is_file():
        return False
    if destination.is_file():
        rel = destination.name
        if not dry_run:
            shutil.copy2(destination, backup_dir / rel)
    if not dry_run:
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return True


def run_command(command: list[str], cwd: Path, env: dict[str, str]) -> None:
    print("+", " ".join(command))
    completed = subprocess.run(command, cwd=cwd, env=env)
    if completed.returncode != 0:
        raise MigrationError(f"Command failed with exit code {completed.returncode}: {' '.join(command)}")


def main() -> int:
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--old-root", required=True, help="Original/upstream NPPS4 deployment or source root")
    parser.add_argument("--new-root", required=True, help="NPPS4 v5.32 root or Android Wrapper source root")
    parser.add_argument("--old-config", help="Explicit old config.toml")
    parser.add_argument("--new-config", help="Existing target config.toml or config.sample.toml")
    parser.add_argument(
        "--legacy-profile", choices=("cn", "gl"), default="gl",
        help="Profile assigned to pre-dual-profile accounts and old download backend. Upstream NPPS4 is normally GL.",
    )
    parser.add_argument(
        "--preserve-other-profile", action="store_true",
        help="Keep the other profile exactly as configured in the target config; otherwise disable it for a safe first boot.",
    )
    parser.add_argument("--python", default=sys.executable, help="Python executable with v5.32 dependencies installed")
    parser.add_argument("--skip-alembic", action="store_true")
    parser.add_argument("--skip-fixes", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    old_root = detect_core_root(Path(args.old_root).expanduser().resolve())
    new_root = detect_core_root(Path(args.new_root).expanduser().resolve())
    old_config_path = find_config(old_root, args.old_config, target=False)
    target_config_source = find_config(new_root, args.new_config, target=True)
    output_config_path = new_root / "config.toml"

    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_dir = new_root / f"migration-backup-{stamp}"
    if not args.dry_run:
        backup_dir.mkdir(parents=True, exist_ok=False)

    old_config = load_toml(old_config_path)
    target_config = load_toml(target_config_source)
    merged_config = migrate_download_config(
        target_config, old_config, args.legacy_profile, args.preserve_other_profile
    )

    # Keep the target database URL aligned with the migrated SQLite file.
    old_db_url = str(old_config.get("database", {}).get("url", "sqlite+aiosqlite:///data/main.sqlite3"))
    source_db = sqlite_path_from_url(old_db_url, old_root)
    target_db_url = str(merged_config.get("database", {}).get("url", "sqlite+aiosqlite:///data/main.sqlite3"))
    target_db = sqlite_path_from_url(target_db_url, new_root)
    if source_db is None:
        print("External database detected. No database bytes will be copied.")
        print("v5.32 will keep the configured database URL and Alembic will upgrade that database in place.")
    else:
        if target_db is None:
            raise MigrationError("Old database is SQLite but target database URL is not SQLite")
        print(f"SQLite source: {source_db}")
        print(f"SQLite target: {target_db}")
        sqlite_integrity(source_db)
        if target_db.is_file() and not args.dry_run:
            shutil.copy2(target_db, backup_dir / "target-main.sqlite3.before-migration")
        if not args.dry_run:
            sqlite_backup(source_db, target_db)

    if output_config_path.is_file() and not args.dry_run:
        shutil.copy2(output_config_path, backup_dir / "config.toml.before-migration")
    if not args.dry_run:
        output_config_path.write_text(dump_toml(merged_config), encoding="utf-8")
    print(f"Config output: {output_config_path}")

    # Preserve the old signing key and custom scripts referenced by config.
    copied: list[str] = []
    key_rel = str(old_config.get("main", {}).get("server_private_key", "default_server_key.pem"))
    if copy_if_present(old_root / key_rel, new_root / key_rel, backup_dir, args.dry_run):
        copied.append(key_rel)
    for rel in ("external", "beatmaps", "templates", "static"):
        src = old_root / rel
        dst = new_root / rel
        if src.is_dir():
            if not args.dry_run:
                shutil.copytree(src, dst, dirs_exist_ok=True)
            copied.append(rel + "/")

    old_server_data_path = old_root / str(old_config.get("main", {}).get("server_data", "npps4/server_data.json"))
    target_server_data_path = new_root / str(
        merged_config.get("main", {}).get("server_data", "npps4/server_data.json")
    )
    conflicts: list[str] = []
    if old_server_data_path.is_file() and target_server_data_path.is_file():
        vanilla_reference = json.loads(VANILLA_SERVER_DATA_REFERENCE.read_text(encoding="utf-8"))
        old_server_data = json.loads(old_server_data_path.read_text(encoding="utf-8"))
        target_server_data = json.loads(target_server_data_path.read_text(encoding="utf-8"))
        merged_server_data = three_way_merge(vanilla_reference, old_server_data, target_server_data, conflicts)
        if not args.dry_run:
            shutil.copy2(target_server_data_path, backup_dir / "server_data.json.before-migration")
            target_server_data_path.write_text(
                json.dumps(merged_server_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
        print(f"server_data output: {target_server_data_path}")
    else:
        print("server_data merge skipped because an input file is missing")

    env = os.environ.copy()
    env["NPPS4_CONFIG"] = str(output_config_path)
    if not args.dry_run and not args.skip_alembic:
        run_command([args.python, "-m", "alembic", "upgrade", "head"], new_root, env)
    if not args.dry_run and not args.skip_fixes:
        run_command([args.python, "-m", "npps4.script", "scripts/apply_fixes.py"], new_root, env)

    report = {
        "old_root": str(old_root),
        "new_root": str(new_root),
        "legacy_profile": args.legacy_profile,
        "source_database": str(source_db) if source_db else old_db_url,
        "target_database": str(target_db) if target_db else target_db_url,
        "copied_paths": copied,
        "server_data_conflicts": conflicts,
        "backup_directory": str(backup_dir),
        "dry_run": args.dry_run,
    }
    report_path = new_root / f"migration-report-{stamp}.json"
    if not args.dry_run:
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if conflicts:
        print(f"WARNING: {len(conflicts)} server_data merge conflict(s); see {report_path}")
    print("Migration completed. Start v5.32 normally and inspect its first boot log before exposing it publicly.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except MigrationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
