[main]
data_directory = "data"
secret_key = "Change this secret"
server_private_key = "default_server_key.pem"
server_private_key_password = ""
server_data = "npps4/server_data.json"
session_expiry = 259200
save_notes_list = false

[database]
url = "sqlite+aiosqlite:///data/main.sqlite3"

[download]
backend = "n4dlapi"
send_patched_server_info = true

[download.n4dlapi]
server = "https://ll.sif.moe/npps4_dlapi/"
shared_key = ""

[game]
badwords = "external/badwords.py"
login_bonus = "external/login_bonus.py"
beatmaps = "external/beatmap.py"
live_unit_drop = "external/live_unit_drop.py"
live_box_drop = "external/live_box_drop.py"

[advanced]
base_xorpad = "eit4Ahph4aiX4ohmephuobei6SooX9xo"
application_key = "b6e6c940a93af2357ea3e0ace0b98afc"
consumer_key = "lovelive_test"
verify_xmc = true

[compat]
region = "global"
cn_main_headers = false
cn_autocreate_ghome_users = false
cn_wrappers = false
cn_optional_stubs = false
daily_rotation_timezone = "auto"
live_continue_loveca_cost = 1

[iex]
enable_export = true
enable_import = true
bypass_signature = false

[gameplay]
energy_multiplier = 1
love_multiplier = 1
secretbox_cost_multiplier = 1
